export const VALID_STATES = [
    'AK',
    'AR',
    'CA',
    'CO',
    'DC',
    'FL',
    'GA',
    'HI',
    'IL',
    'KS',
    'KY',
    'MN',
    'NE',
    'NM',
    'NY',
    'NC',
    'ND',
    'OK',
    'OR',
    'RI',
    'SC',
    'SD',
    'TX',
    'UT',
    'VT',
    'WV',
    'WI',
    'WY',

    // 'AL',
    // 'AS',
    // 'AZ',
    // 'CT',
    // 'DE',
    // 'FM',
    // 'GU',
    // 'ID',
    // 'IN',
    // 'IA',
    // 'LA',
    // 'ME',
    // 'MH',
    // 'MD',
    // 'MA',
    // 'MI',
    // 'MS',
    // 'MO',
    // 'MT',
    // 'NV',
    // 'NH',
    // 'NJ',
    // 'MP',
    // 'OH',
    // 'PW',
    // 'PA',
    // 'PR',
    // 'TN',
    // 'VI',
    // 'VA',
    // 'WA',

    // CANADIAN STATES
    'AB',
    'BC',
    'MB',
    'NB',
    'NL',
    'NT',
    'NS',
    'NU',
    'ON',
    'PE',
    'QC',
    'SK',
    'YT',
];

export const DEV_VALID_STATES = ['GA', 'UP', 'TN', 'WB', 'AS', 'Méx.'];

export const VALID_COUNTRIES = ['US', 'CA'];

export const DEV_VALID_COUNTRIES = ['IN', 'MX'];

export const US_STATE_PERMISSIONS = [
    {
        name: 'Alabama',
        abbr: 'AL',
        appAccess: true,
        paidContests: false,
        minAge: 19,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Alaska',
        abbr: 'AK',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Arizona',
        abbr: 'AZ',
        appAccess: true,
        paidContests: false,
        minAge: 21,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Arkansas',
        abbr: 'AR',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'California',
        abbr: 'CA',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Colorado',
        abbr: 'CO',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: false,
    },
    {
        name: 'Connecticut',
        abbr: 'CT',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Delaware',
        abbr: 'DE',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'District of Columbia',
        abbr: 'DC',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Florida',
        abbr: 'FL',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Georgia',
        abbr: 'GA',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Hawaii',
        abbr: 'HI',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Idaho',
        abbr: 'ID',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Illinois',
        abbr: 'IL',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Indiana',
        abbr: 'IN',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Iowa',
        abbr: 'IA',
        appAccess: true,
        paidContests: false,
        minAge: 21,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Kansas',
        abbr: 'KS',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Kentucky',
        abbr: 'KY',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Louisiana',
        abbr: 'LA',
        appAccess: true,
        paidContests: false,
        minAge: 21,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Maine',
        abbr: 'ME',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Maryland',
        abbr: 'MD',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 500000,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Massachusetts',
        abbr: 'MA',
        appAccess: true,
        paidContests: true,
        minAge: 21,
        weeklyDepositLimit: 100000,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Michigan',
        abbr: 'MI',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Minnesota',
        abbr: 'MN',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Mississippi',
        abbr: 'MS',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Missouri',
        abbr: 'MO',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Montana',
        abbr: 'MT',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Nebraska',
        abbr: 'NE',
        appAccess: true,
        paidContests: true,
        minAge: 19,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Nevada',
        abbr: 'NV',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'New Hampshire',
        abbr: 'NH',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'New Jersey',
        abbr: 'NJ',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'New Mexico',
        abbr: 'NM',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'New York',
        abbr: 'NY',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'North Carolina',
        abbr: 'NC',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'North Dakota',
        abbr: 'ND',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Ohio',
        abbr: 'OH',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Oklahoma',
        abbr: 'OK',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Oregon',
        abbr: 'OR',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Pennsylvania',
        abbr: 'PA',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Rhode Island',
        abbr: 'RI',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'South Carolina',
        abbr: 'SC',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'South Dakota',
        abbr: 'SD',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Tennessee',
        abbr: 'TN',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 250000,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Texas',
        abbr: 'TX',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Utah',
        abbr: 'UT',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Vermont',
        abbr: 'VT',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Virginia',
        abbr: 'VA',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Washington',
        abbr: 'WA',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'West Virginia',
        abbr: 'WV',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Wisconsin',
        abbr: 'WI',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Wyoming',
        abbr: 'WY',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'American Somoa',
        abbr: 'AS',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Guam',
        abbr: 'GU',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Northern Mariana Islands',
        abbr: 'MP',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Puerto Rico',
        abbr: 'PR',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'US Virgin Islands',
        abbr: 'VI',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'US Minor Outlying Islands',
        abbr: 'UM',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Micronesia',
        abbr: 'FM',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Marshall Islands',
        abbr: 'MH',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Palau',
        abbr: 'PW',
        appAccess: true,
        paidContests: false,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
];

export const CANADA_STATE_PERMISSIONS = [
    {
        name: 'Alberta',
        abbr: 'AB',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'British Columbia',
        abbr: 'BC',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Manotiba',
        abbr: 'MB',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'New Brunswick',
        abbr: 'NB',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Newfoundland and Labrador',
        abbr: 'NL',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Nova Scotia',
        abbr: 'NS',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Ontario',
        abbr: 'ON',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Prince Edward Island',
        abbr: 'PE',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Quebec',
        abbr: 'QC',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Saskatchewan',
        abbr: 'SK',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Northwest Territories',
        abbr: 'NT',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Yukon',
        abbr: 'YT',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Nunavut',
        abbr: 'NU',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
];

export const VALID_STATE_PERMISSIONS = [...US_STATE_PERMISSIONS, ...CANADA_STATE_PERMISSIONS];

export const DEV_STATE_PERMISSIONS = [
    {
        name: 'GA',
        abbr: 'GA',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'UP',
        abbr: 'UP',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'TN',
        abbr: 'TN',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'WB',
        abbr: 'WB',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'AS',
        abbr: 'AS',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
    {
        name: 'Méx.',
        abbr: 'Méx.',
        appAccess: true,
        paidContests: true,
        minAge: 18,
        weeklyDepositLimit: 0,
        leaguesEnabled: true,
        battlegroundEnabled: true,
    },
];

export const FALLBACK_PERMISSIONS = {
    appAccess: true,
    paidContests: false,
    minAge: 18,
    weeklyDepositLimit: 0,
    leaguesEnabled: true,
    battlegroundEnabled: true,
};
