export const PERMISSIONS = {
    BETS: {
        VIEW_ALL_BETS: 'viewAllBets',
        VIEW_ANY_BET: 'viewAnyBet',
        COUNT_BETS: 'countBets',
    },
    CONTACT_SUBMISSIONS: {
        VIEW_ALL_CONTACT_SUBMISSIONS: 'viewAllContactSubmissions',
        VIEW_ANY_CONTACT_SUBMISSION: 'viewAnyContactSubmission',
        CREATE_ANY_CONTACT_SUBMISSION: 'createAnyContactSubmission',
        UN_READ_ANY_CONTACT_SUBMISSION: 'unReadAnyContactSubmission',
        REPLY_ANY_CONTACT_SUBMISSION: 'replyAnyContactSubmission',
        DELETE_ANY_CONTACT_SUBMISSION: 'deleteAnyContactSubmission',
        ARCHIVE_ANY_CONTACT_SUBMISSION: 'archiveAnyContactSubmission',
        COUNT_CONTACT_SUBMISSIONS: 'countContactSubmissions',
    },
    CONTENDERS: {
        VIEW_ALL_CONTENDERS: 'viewAllContenders',
        VIEW_ANY_CONTENDER: 'viewAnyContender',
        CREATE_ANY_CONTENDER: 'createAnyContender',
        // UPDATE_ANY_CONTENDER: 'updateAnyContender',
        // DELETE_ANY_CONTENDER: 'deleteAnyContender',
        // ARCHIVE_ANY_CONTENDER: 'archiveAnyContender',
        COUNT_CONTENDERS: 'countContenders',
    },
    CONTESTS: {
        VIEW_ALL_CONTESTS: 'viewAllContests',
        // VIEW_LEAD_STATUS_STATISTIC: 'viewLeadStatusStatistic',
        VIEW_CONVERSION_STATISTIC: 'viewConversionStatistic',
        VIEW_ALL_CONTESTS_TOTAL: 'viewAllContestsTotal',
        VIEW_ANY_CONTEST: 'viewAnyContest',
        CREATE_ANY_CONTEST: 'createAnyContest',
        UPDATE_ANY_CONTEST: 'updateAnyContest',
        DELETE_ANY_CONTEST: 'deleteAnyContest',
        ARCHIVE_ANY_CONTEST: 'archiveAnyContest',
        COUNT_CONTESTS: 'countContests',
        CALCULATE_AMOUNTS: 'calculateAmounts',
    },
    GAINS: {
        VIEW_ALL_GAINS: 'viewAllGains',
        VIEW_ANY_GAIN: 'viewAnyGain',
        COUNT_GAINS: 'countGains',
    },
    GAMES: {
        VIEW_ALL_GAMES: 'viewAllGames',
        VIEW_ANY_GAME: 'viewAnyGame',
        COUNT_GAMES: 'countGames',
    },
    NFL_DETAILS: {
        VIEW_WEEK_DETAILS: 'viewWeekDetails',
        VIEW_SEASON_DETAILS: 'viewSeasonDetails',
        VIEW_SCHEDULE_DETAILS: 'viewScheduleDetails',
        VIEW_TIME_FRAMES: 'viewTimeFrames',
    },
    PLAYERS: {
        VIEW_ALL_PLAYERS: 'viewAllPlayers',
        VIEW_ANY_PLAYER: 'viewAnyPlayer',
        // CREATE_ANY_PLAYER: 'createAnyPlayer',
        // UPDATE_ANY_PLAYER: 'updateAnyPlayer',
        DELETE_ANY_PLAYER: 'deleteAnyPlayer',
        // ARCHIVE_ANY_PLAYER: 'archiveAnyPlayer',
        COUNT_PLAYERS: 'countPlayers',
        IMPORT_PLAYERS: 'importPlayers',
        EXPORT_PLAYERS: 'exportPlayers',
    },
    USERS: {
        VIEW_ALL_USERS: 'viewAllUsers',
        VIEW_ANY_USER: 'viewAnyUser',
        CREATE_ANY_USER: 'createAnyUser',
        UPDATE_ANY_USER: 'updateAnyUser',
        DELETE_ANY_USER: 'deleteAnyUser',
        ARCHIVE_ANY_USER: 'archiveAnyUser',
        COUNT_USERS: 'countUsers',
        RUN_UPDATE_FIXES: 'runUpdatesAndFixes',
        //WALLET
        // UPDATE_PAYMENT_METHODS: 'updatePaymentMethods',
        VIEW_ANY_WALLET_INFO: 'viewAnyWalletInfo',
        UPDATE_ANY_WALLET_INFO: 'updateAnyWalletInfo',
        GENERATE_ACCOUNT_VERIFICATION_TOKEN: 'generateIavToken',
        REMOVE_ANY_FUNDING_SOURCE: 'removeAnyFundingSource',
        VIEW_ANY_FUNDING_SOURCE: 'viewAnyFundingSource',
        VIEW_ANY_WALLET_BALANCE: 'viewAnyWalletBalance',
        FUND_ANY_WALLET: 'fundAnyWallet',
        VIEW_ANY_TRANSFER: 'viewAnyTransfer',
        UPLOAD_VERIFICATION_FILE: 'uploadVerificationFile',
    },
    TEAMS: {
        VIEW_ALL_TEAMS: 'viewAllTeams',
        VIEW_ANY_TEAM: 'viewAnyTeam',
        COUNT_TEAMS: 'countTeams',
    },
    TOP_UPS: {
        VIEW_ALL_TOP_UPS: 'viewAllTopUps',
        VIEW_ANY_TOP_UP: 'viewAnyTopUp',
        // CREATE_ANY_TOP_UP: 'createAnyTopUp',
        // UPDATE_ANY_TOP_UP: 'updateAnyTopUp',
        // DELETE_ANY_TOP_UP: 'deleteAnyTopUp',
        // ARCHIVE_ANY_TOP_UP: 'archiveAnyTopUp',
        COUNT_TOP_UPS: 'countTopUps',
    },
    WITHDRAW_REQUESTS: {
        CREATE_ANY_WITHDRAW_REQUESTS: 'createAnyWithdrawRequests',
        VIEW_ALL_WITHDRAW_REQUESTS: 'viewAllWithdrawRequests',
        VIEW_ANY_WITHDRAW_REQUEST: 'viewAnyWithdrawRequest',
        UPDATE_ANY_WITHDRAW_REQUEST: 'updateAnyWithdrawRequest',
        COUNT_WITHDRAW_REQUESTS: 'countWithdrawRequests',
    },
};

export enum ROLES {
    ADMIN = 'admin',
    USER = 'user',
}
