const sevenToEighteenSeeder = [
    {
        projectionSpread:  50,
        spread:  47,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  49.5,
        spread:  47,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  49,
        spread:  46,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  48.5,
        spread:  46,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  48,
        spread:  45,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  47.5,
        spread:  45,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  47,
        spread:  44,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  46.5,
        spread:  44,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  46,
        spread:  43,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  45.5,
        spread:  43,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  45,
        spread:  42,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  44.5,
        spread:  42,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  44,
        spread:  41,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  43.5,
        spread:  41,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  43,
        spread:  40,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  42.5,
        spread:  40,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  42,
        spread:  39,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  41.5,
        spread:  39,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  41,
        spread:  38,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  40.5,
        spread:  38,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  40,
        spread:  37,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  39.5,
        spread:  37,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  39,
        spread:  36,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  38.5,
        spread:  36,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  38,
        spread:  35,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  37.5,
        spread:  35,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  37,
        spread:  34,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  36.5,
        spread:  34,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  36,
        spread:  33,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  35.5,
        spread:  33,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  35,
        spread:  32,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  34.5,
        spread:  32,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  34,
        spread:  31,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  33.5,
        spread:  31,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  33,
        spread:  30,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  32.5,
        spread:  30,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  32,
        spread:  29,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  31.5,
        spread:  29,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  31,
        spread:  28,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  30.5,
        spread:  28,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  30,
        spread:  27,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  29.5,
        spread:  27,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  29,
        spread:  26,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  28.5,
        spread:  26,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  28,
        spread:  25,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  27.5,
        spread:  25,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  27,
        spread:  24,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  26.5,
        spread:  24,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  26,
        spread:  23,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  25.5,
        spread:  23,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  25,
        spread:  22,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  24.5,
        spread:  22,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  24,
        spread:  21,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  23.5,
        spread:  21,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  23,
        spread:  20,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  22.5,
        spread:  20,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  22,
        spread:  19,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  21.5,
        spread:  19,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  21,
        spread:  18,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  20.5,
        spread:  18,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  20,
        spread:  17,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  19.5,
        spread:  17,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  19,
        spread:  16,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  18.5,
        spread:  16,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  18,
        spread:  15,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  17.5,
        spread:  15,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  17,
        spread:  14,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  16.5,
        spread:  14,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  16,
        spread:  13,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  15.5,
        spread:  13,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  15,
        spread:  12,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  14.5,
        spread:  12,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  14,
        spread:  11,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  13.5,
        spread:  11,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  13,
        spread:  10,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  12.5,
        spread:  10,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  12,
        spread:  9,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  11.5,
        spread:  9,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  11,
        spread:  8,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  10.5,
        spread:  8,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  10,
        spread:  7,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  9.5,
        spread:  7,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  9,
        spread:  6,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  8.5,
        spread:  6,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  8,
        spread:  5,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  7.5,
        spread:  5,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  7,
        spread:  4,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  6.5,
        spread:  4,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  6,
        spread:  3,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  5.5,
        spread:  3,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  5,
        spread:  2,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  4.5,
        spread:  2,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  4,
        spread:  1,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  3.5,
        spread:  1,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  3,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  2.5,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  2,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  1.5,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  1,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  0.5,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  0,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  0,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -0.5,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -1,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -1.5,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -2,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -2.5,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -3,
        spread:  0,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -3.5,
        spread:  -1,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -4,
        spread:  -1,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -4.5,
        spread:  -2,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -5,
        spread:  -2,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -5.5,
        spread:  -3,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -6,
        spread:  -3,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -6.5,
        spread:  -4,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -7,
        spread:  -4,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -7.5,
        spread:  -5,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -8,
        spread:  -5,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -8.5,
        spread:  -6,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -9,
        spread:  -6,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -9.5,
        spread:  -7,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -10,
        spread:  -7,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -10.5,
        spread:  -8,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -11,
        spread:  -8,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -11.5,
        spread:  -9,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -12,
        spread:  -9,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -12.5,
        spread:  -10,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -13,
        spread:  -10,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -13.5,
        spread:  -11,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -14,
        spread:  -11,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -14.5,
        spread:  -12,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -15,
        spread:  -12,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -15.5,
        spread:  -13,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -16,
        spread:  -13,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -16.5,
        spread:  -14,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -17,
        spread:  -14,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -17.5,
        spread:  -15,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -18,
        spread:  -15,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -18.5,
        spread:  -16,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -19,
        spread:  -16,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -19.5,
        spread:  -17,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -20,
        spread:  -17,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -20.5,
        spread:  -18,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -21,
        spread:  -18,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -21.5,
        spread:  -19,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -22,
        spread:  -19,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -22.5,
        spread:  -20,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -23,
        spread:  -20,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -23.5,
        spread:  -21,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -24,
        spread:  -21,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -24.5,
        spread:  -22,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -25,
        spread:  -22,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -25.5,
        spread:  -23,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -26,
        spread:  -23,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -26.5,
        spread:  -24,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -27,
        spread:  -24,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -27.5,
        spread:  -25,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -28,
        spread:  -25,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -28.5,
        spread:  -26,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -29,
        spread:  -26,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -29.5,
        spread:  -27,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -30,
        spread:  -27,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -30.5,
        spread:  -28,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -31,
        spread:  -28,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -31.5,
        spread:  -29,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -32,
        spread:  -29,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -32.5,
        spread:  -30,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -33,
        spread:  -30,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -33.5,
        spread:  -31,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -34,
        spread:  -31,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -34.5,
        spread:  -32,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -35,
        spread:  -32,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -35.5,
        spread:  -33,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -36,
        spread:  -33,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -36.5,
        spread:  -34,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -37,
        spread:  -34,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -37.5,
        spread:  -35,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -38,
        spread:  -35,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -38.5,
        spread:  -36,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -39,
        spread:  -36,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -39.5,
        spread:  -37,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -40,
        spread:  -37,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -40.5,
        spread:  -38,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -41,
        spread:  -38,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -41.5,
        spread:  -39,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -42,
        spread:  -39,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -42.5,
        spread:  -40,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -43,
        spread:  -40,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -43.5,
        spread:  -41,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -44,
        spread:  -41,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -44.5,
        spread:  -42,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -45,
        spread:  -42,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -45.5,
        spread:  -43,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -46,
        spread:  -43,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -46.5,
        spread:  -44,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -47,
        spread:  -44,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -47.5,
        spread:  -45,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -48,
        spread:  -45,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -48.5,
        spread:  -46,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -49,
        spread:  -46,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -49.5,
        spread:  -47,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
    {
        projectionSpread:  -50,
        spread:  -47,
        spreadPay:  1.0,
        ml:  0,
        mlPay:  0,
        spreadType: 'league_7_to_18',
    },
];

export default sevenToEighteenSeeder;
