const lobbySeeder = [
    {
        projectionSpread:  6.5,
        spread:  6.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  6,
        spread:  6,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  5.5,
        spread:  5.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  5,
        spread:  5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  4.5,
        spread:  4.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  4,
        spread:  4,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  3.5,
        spread:  3.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  3,
        spread:  3,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  2.5,
        spread:  2.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  2,
        spread:  2,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  1.5,
        spread:  1.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  1,
        spread:  1,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  0.5,
        spread:  0.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  0,
        spread:  0,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -0.5,
        spread:  -0.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -1,
        spread:  -1,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -1.5,
        spread:  -1.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -2,
        spread:  -2,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -2.5,
        spread:  -2.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -3,
        spread:  -3,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -3.5,
        spread:  -3.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -4,
        spread:  -4,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -4.5,
        spread:  -4.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -5,
        spread:  -5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -5.5,
        spread:  -5.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -6,
        spread:  -6,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
    {
        projectionSpread:  -6.5,
        spread:  -6.5,
        spreadPay:  0.9,
        ml:  0,
        mlPay:  0,
        spreadType: 'lobby',
    },
];

export default lobbySeeder;
